version: '3.9'

services:
    server:
        build: 
            context: ./server
            dockerfile: Dockerfile
        image: myapp-server
        container_name: myapp-node-server
        command: npm run start
        volumes: 
            - ./server/:/usr/src/app
            - /usr/src/app/node_modules
        ports:
            - "5000:5000"
        depends_on: 
            - mongo
        networks: 
            - app-network
    mongo:
        image: mongo
        volumes:
            - data-volume:/data/db
        ports:
            - "27017:27017"
        networks: 
            - app-network
    public:
        build: 
            context: ./public
            dockerfile: Dockerfile
        image: myapp-client
        container_name: myapp-react
        command: npm run start
        volumes:
            - ./public/:/usr/app
            - /usr/app/node_modules
        depends_on: 
            - server
        ports: 
            - "3000:3000"
        networks: 
            - app-network
        
networks: 
    app-network:
        driver: bridge

volumes:
    data-volume:
    node_modules:
    web-root:
        driver: local